name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          echo "Syncing files to container..."
          rsync -av ./ /root/ros2_ws/src/mypkg/

          echo "Checking files in /root/ros2_ws/src/mypkg/..."
          ls -la /root/ros2_ws/src/mypkg/

          echo "Building the workspace..."
          cd /root/ros2_ws
          colcon build
          if [ $? -ne 0 ]; then
            echo "Colcon build failed"
            exit 1
          fi

          echo "Sourcing environment..."
          source /root/ros2_ws/install/setup.bash
          if [ $? -ne 0 ]; then
            echo "Failed to source environment"
            exit 1
          fi

          echo "Running the launch file..."
          timeout 10 ros2 launch mypkg talk_listen.launch.py > /tmp/mypkg.log

          echo "Checking the logs for '7倍した結果'..."
          cat /tmp/mypkg.log
          grep '7倍した結果' /tmp/mypkg.log
          if [ $? -ne 0 ]; then
            echo "'7倍した結果' not found in log"
            exit 1
          fi

          echo "Test completed successfully!"

